### PR TITLE
Update UG 

### PR DESCRIPTION
**Pull request by HynRidge**
Include Find Command and Label feature in the UG

### CODE REVIEW

**Review by luo-git — APPROVED** [review]
LGTM!

**Review by anthony6401 — APPROVED** [review]
LGTM!

**Review by luo-git — CHANGES_REQUESTED** [review]
I know it's not because of your changes, but the format is kinda broken. Could you fix that if possible?

This is at the start of the document. (need space after #)
image

**Review by luo-git — APPROVED** [review]
Good job! LGTM!

**Pull request merged**
