### PR TITLE
Add Title for the UI selection window

### PR DESCRIPTION
**Pull request by Ma-Yueran**
Forgot to add the title for the previous PR.

### CODE REVIEW

**Review by HynRidge — APPROVED** [review]
LGTM

**Review by luo-git — APPROVED** [review]

**Comment by Ma-Yueran** [comment]
Update PR to add a new Theme, also replace AB3 icon with new icon.

**Review by luo-git — APPROVED** [review]
Great job on CSS. Looks real good.

**Comment by Ma-Yueran** [comment]
Thanks

> Great job on CSS. Looks real good.

**Pull request merged**
