### PR TITLE
Add New Themes for UI

### PR DESCRIPTION
**Pull request by Ma-Yueran**
Galaxy Theme: 
galaxy_theme
Sky Theme (Cannot think of a better name...)
sky_theme

### CODE REVIEW

**Review by luo-git — CHANGES_REQUESTED** [review]
Looks good. The words in galaxy theme is a bit hard to read though.

Another thing, could you update the UG as well?

**Comment by Ma-Yueran** [comment]
> Looks good. The words in galaxy theme is a bit hard to read though.
> 
> Another thing, could you update the UG as well?

Sure, I try to add theme switching to UG

**Comment by Ma-Yueran** [comment]
> > Looks good. The words in galaxy theme is a bit hard to read though.
> > Another thing, could you update the UG as well?
> 
> Sure, I try to add theme switching to UG

Ooo, just found it's already added, then I will update the images.

**Comment by luo-git** [comment]
> > > Looks good. The words in galaxy theme is a bit hard to read though.
> > > Another thing, could you update the UG as well?
> > 
> > 
> > Sure, I try to add theme switching to UG
> 
> Ooo, just found it's already added, then I will update the images.

The `changing theme` section is not updated to reflect your changes. Could you also update the screenshot if possible?

Changing themes
HelloFile comes in light and dark themes. ...

**Comment by Ma-Yueran** [comment]
> > > > Looks good. The words in galaxy theme is a bit hard to read though.
> > > > Another thing, could you update the UG as well?
> > > 
> > > 
> > > Sure, I try to add theme switching to UG
> > 
> > 
> > Ooo, just found it's already added, then I will update the images.
> 
> The `changing theme` section is not updated to reflect your changes. Could you also update the screenshot if possible?
> 
> Changing themes
> HelloFile comes in light and dark themes. ...

Sure, I'm doing that now

**Comment by Ma-Yueran** [comment]
The color of the edge of the window for me is white,
changing_themes2

But others are blue,
changing_themes

How do I modify the color to make it consistent?

**Comment by Ma-Yueran** [comment]
Galaxy Theme is modified to make fonts clearer,

**Comment by Ma-Yueran** [comment]
Galaxy Theme is updated to make fonts clearer,

**Comment by luo-git** [comment]
> How do I modify the color to make it consistent?

Doesn't matter for now. We probably need to change those screenshots later because the words are too small...😢

**Review by luo-git — APPROVED** [review]
LGTM!

**Pull request merged**
