### PR TITLE
Implement Dark Theme UI

### LINKED ISSUE #97: Implement Dark Theme style for UI
Make UI looks better.

### PR DESCRIPTION
**Pull request by Ma-Yueran**
屏幕截图 2020-10-14 020551

Make UI look darker

Rename CommandBox -> OldCommanBox, NewCommandBox -> CommandBox

### CODE REVIEW

**Review by luo-git — COMMENTED** [review]
Looks good. Is it possible to have a toggle for this theme?

**Comment by Ma-Yueran** [comment]
> Looks good. Is it possible to have a toggle for this theme?

You mean something to switch to different themes?

**Comment by Ma-Yueran** [comment]
The PR update modifies the Version variable in MainApp in fit the current milestone, and display that version number in UI.

**Comment by luo-git** [comment]
> > Looks good. Is it possible to have a toggle for this theme?
> 
> You mean something to switch to different themes?

Yup

**Review by luo-git — APPROVED** [review]
LGTM

**Comment by Ma-Yueran** [comment]
Ok, working on it now

**Comment by Ma-Yueran** [comment]
Update PR to support UI theme switching.

**Review by HynRidge — APPROVED** [review]
Nice Theme..
LGTM!!

**Pull request merged**
